### PR TITLE
Fix Repeat expander in JSON Context

### LINKED ISSUE #150: Can't make array Repeat expander working in JSON context
Or maybe I am using it wrong way?

First I've tried:
```
"@array@.repeat({"name": "@string@", "value": "@array@"})"
```
Which gives confusing error: `RuntimeException: Type pattern "@array@" is not supported by TextMatcher.`

Then I've tried:
```
"@array@.repeat({\"name\": \"@string@\", \"value\": \"@array@\"})"
```
But that one also gives an error:
```
      Behat\Testwork\Call\Exception\FatalThrowableError: Type error: Argument 1 passed to Coduo\PHPMatcher\Matcher\Pattern\Expander\Repeat::__construct() must be of the type string, array given in vendor/coduo/php-matcher/src/Matcher/Pattern/Expander/Repeat.php:29
      Stack trace:
      #0 [internal function]: Coduo\PHPMatcher\Matcher\Pattern\Expander\Repeat->__construct(Array)
      #1 vendor/coduo/php-matcher/src/Parser/ExpanderInitializer.php(79): ReflectionClass->newInstanceArgs(Array)
```
Repeat matcher expects argument to be json encoded string but ExpanderInitializer gives to it already decoded json array. It can be fixed by allowing Repeat expander to accept arrays too.

### PR DESCRIPTION
**Pull request by JarJak**
Fixes #150

### CODE REVIEW

**Comment by norzechowicz** [comment]
Hey @JarJak looks good but could you please add test with example of repeat expander usage that wasn't working previously?

**Comment by JarJak** [comment]
@norzechowicz sure! Can you guide me how to test if an expander works fine with JsonMatcher?

**Comment by norzechowicz** [comment]
Maybe try from testing example that wasn't working for you in #150 

```
"@array@.repeat({"name": "@string@", "value": "@array@"})"
```

This one should works now, right?

**Comment by JarJak** [comment]
@norzechowicz no, this is not a valid JSON. This one should work:
```
"@array@.repeat({\"name\": \"@string@\", \"value\": \"@array@\"})"
```

**Comment by norzechowicz** [comment]
@JarJak I was more thining about adding those tests into this PR so it could actually prove that your fix works :P Could you merge those two?

**Comment by JarJak** [comment]
@norzechowicz they are merged... see changes in this PR

**Comment by norzechowicz** [comment]
right cool thanks!

**Pull request merged**
