### PR TITLE
Add repeat expanders tests

### PR DESCRIPTION
**Pull request by JarJak**
They will fail here

### CODE REVIEW

**Comment by JarJak** [comment]
But in #151 they pass :)

**Comment by peter279k** [comment]
The Travis CI build is failed due to the [PHPMatcher\Matcher\Pattern\Expander\Repeat::__construct constructor](https://github.com/coduo/php-matcher/blob/master/src/Matcher/Pattern/Expander/Repeat.php#L29).

The constructor only accepts the `string` `$pattern`.

If we want ti allow the mixed type for `$pattern` variable, we should remove the `string` type hint inside this constructor.

**Comment by JarJak** [comment]
@peter279k oh, really? It is done in #151

**Comment by peter279k** [comment]
> @peter279k oh, really? It is done in #151

That's right. You can check the Travis CI build log :).

**Pull request closed without merging**
