### PR TITLE
Adds NonStrictArrayMatcher which will matches softly value and pattern

### PR DESCRIPTION
**Pull request by javierseixas**
After studying a bit issue #39 , I found out that the only thing required to be able to match softly a JSON, would be having a new `ArrayMatcher`, being able to keep going through the array instead of returning an error when there is a value not contained in the pattern.
So here it is my proposal of creating a new `NonStrictArrayMatcher`, a subtype of the `ArrayMatcher`, where only changes the `iterateMatch()` method.

So, to get what I requested on issue #39 it would be only needed to create a `JsonMatcher` containing a `NonStrictArrayMatcher`.

### CODE REVIEW

**Comment by javierseixas** [comment]
Hi! Just say that I don't forget this pull request. I've been very busy the last weeks. Hoping to get some free time next month to advance on this :)

**Comment by norzechowicz** [comment]
Hey @javierseixas thanks for information. PR is open, take as long as you need to finish it and let me know if you will need some help.

**Comment by norzechowicz** [comment]
@javierseixas I'm closing this PR for now, if u will find some time to work on it ping me and I will reopen it or create new one on your own.

**Comment by javierseixas** [comment]
@norzechowicz no problem. I'm sorry I haven't had the time to work on this. Thanks!

**Comment by steffenbrem** [comment]
:+1: Like this idea a lot! any update on this?

**Comment by vitalyiegorov** [comment]
👍Any news on this? @javierseixas

**Comment by javierseixas** [comment]
Hi @vitalyiegorov ! No news actually. I haven't been programming with php for a while, so I stop needing that feature. I can say though other languages like java have it.

**Comment by javierseixas** [comment]
My PR is from 2015. Not sure if is still compatible with the current version of the project.
Besides, I didn't apply the last suggestions from the owners of the library, [see comment above](https://github.com/coduo/php-matcher/pull/40#issuecomment-67768629).
In any case, it depends on them. Or maybe someone else can carry on with that PR.

**Pull request closed without merging**
