### PR TITLE
Test for empty array

### PR DESCRIPTION
**Pull request by JarJak**
See #144

### CODE REVIEW

**Comment by norzechowicz** [comment]
Thanks for adding this test, I will try to find some time to fix this one unless you are already working on patch?

**Comment by JarJak** [comment]
No, I haven't started working on it.

**Comment by peter279k** [comment]
The Travis CI build is failed due to failed assertion.

This should check what's this happen.

If this PR is not concerned, this PR I think should be closed until the PR author start working on this :).

**Comment by JarJak** [comment]
@peter279k this is a bug report, why I have to fix it?

**Comment by peter279k** [comment]
@JarJak, thank you for your reply.

That makes sense and I've seen related issue.

**Pull request merged**
