### PR TITLE
Replaced PHPMatcher facade with implementation that makes possible to access backtrace

### PR DESCRIPTION
**Pull request by norzechowicz**
PHPMatcher API cleanup that replaces facade with regular class allowing to access last message/backtrace. 

### Changes

**Creating Matcher:** 
```diff
-$factory = new MatcherFactory();
-$matcher = $factory->createMatcher();
+$matcher = new PHPMatcher();
```

**Using Matcher**
```diff
-PHPMatcher::match($value, $pattern, $error)
+$matcher = (new PHPMatcher())->match($value, $pattern);;
```

**Accessing last error/backtrace**
```diff
+$matcher = new PHPMatcher();
+$matcher->match($value, $pattern);
+echo $matcher->error();
+echo $matcher->backtrace();
```

### CODE REVIEW

**Comment by norzechowicz** [comment]
@lchrusciel could you please check if those changes are not going to impact https://github.com/lchrusciel/ApiTestCase too hard?

**Comment by lchrusciel** [comment]
I will take a look, but we should be fine.

**Comment by norzechowicz** [comment]
Let me know if you notice anything that could be hard to upgrade, I'm merging it for now, thanks!

**Comment by lchrusciel** [comment]
Just to confirm, it's about ~20 lines to make it work on my side. Thanks a lot! Do you have plans to release a new version? I will probably work on ApiTestCase in mid-December.

**Comment by norzechowicz** [comment]
Awesome, I was just waiting for you to confirm that it works, I think I'm going to release it next week - need to check everything one more time and I think we gonna be good to go

**Comment by lchrusciel** [comment]
The current output is really verbose, but I didn't have time to dive deeply and make it nicer: https://travis-ci.org/lchrusciel/ApiTestCase/jobs/618384619#L513

I guess it is just a matter of configuration, some tweaks, or better usage. Tl;dr: it works ;)

**Pull request merged**
