### PR TITLE
Added php 7 support

### PR DESCRIPTION
**Pull request by norzechowicz**

### CODE REVIEW

**Comment by lchrusciel** [comment]
Thank you!

**Comment by norzechowicz** [comment]
@lchrusciel your welcome :) I'm going to release 2.0.0 in few days

**Comment by lchrusciel** [comment]
Sure thing. We will work with minimum-stability dev for couple of days.

**Comment by norzechowicz** [comment]
awsome!

**Comment by munkie** [comment]
@norzechowicz any plans on releasing 2.0? A month has passed since your promise )

**Comment by norzechowicz** [comment]
@munkie sorry that I make u wait so long, here is how I see the release process of version 2.0.0 https://github.com/coduo/php-matcher/issues/66

**Pull request merged**
