### PR TITLE
Possibility to use expanders for multiple matchers

### PR DESCRIPTION
**Pull request by SpartakusMd**
Following matchers coulnd't have expanders :
- BooleanMatcher
- NumberMatcher
- UuidMatcher

### CODE REVIEW

**Comment by SpartakusMd** [comment]
P.S. @norzechowicz can I ask you to tag a new release in order to not use dev-master in composer ?

**Comment by norzechowicz** [comment]
hey @SpartakusMd thanks for your contribution, it looks useful! 
Could you please add usage of those expanders into tests? 
Also what use case do you have for adding expanders into null & boolean matchers?

**Comment by SpartakusMd** [comment]
@norzechowicz, for  null matcher I don't have a use for the expanders, but I considered it's better to have the possibility to have the expanders and like so all the matchers are more similar.

For the boolean matcher I use the optional expander. We do functional API tests, and have a model that is extended and when you need to test an API that can return one variant of the extended model you should have the ability to mark some fields as optional.

I'll add the tests when I'll have some time.

**Comment by norzechowicz** [comment]
> for null matcher I don't have a use for the expanders, but I considered it's better to have the possibility to have the expanders and like so all the matchers are more similar

So please remove it, adding this possibility also means it needs to be supported as long as version 3.0.0 will be supported. 

> I'll add the tests when I'll have some time.

Thanks!

**Comment by SpartakusMd** [comment]
@norzechowicz I added some tests. Should I add more ?

**Comment by norzechowicz** [comment]
Hey @SpartakusMd looks good, thanks! 🍻

**Pull request merged**
