### PR TITLE
[WIP] Match expander #35

### PR DESCRIPTION
**Pull request by partikus**
Still in progress.

### CODE REVIEW

**Comment by partikus** [comment]
Matcher expander does not work with `TextMatcher` and `JsonMatcher` yet. 
Replacement `@json@` with regex converter under `TextMatcher` need bigger effort. 

Problem only occurs for cases when `JSON` pattern has multilines:

WRONG:
```php

$value = <<<TXT
{
    "users": [
        {
            "url": "https://google.com"
        }
    ]
}
TXT;

$pattern = '{
    "users": @json@.match(
        {
            "url": "@string@.isUrl()"
        }
    )
}';
```

OK:
```php
$value = <<<TXT
{
    "users": [
        {
            "name": "Johny Deep"
        }
    ]
}
TXT;

$pattern = json_encode([
    "users" => sprintf("@json@.match(%s)", json_encode([
        "name" => '@string@'
    ]))
]);
```

I tried to change `TextMatcher::PATTERN_REGEXP` by adding line break chars etc but no success

**Comment by norzechowicz** [comment]
Thanks for your work, let me review that next week (busy weekend) and I will back to you with some feedback

**Comment by shakaran** [comment]
@norzechowicz any progress checking and reviewing this PR?

**Comment by norzechowicz** [comment]
hey @partikus any chance you could rebase this one? I know it's old, if you don't have time I can do it. 
I just found another valid use case for JsonObjectMatcher and `match` expander.

https://github.com/coduo/php-matcher/issues/133

This PR would allow to do something similar to:
```
{
  "image": "@json@.oneOf(optional(), match(...))"
}
```
or

```
{
  "image": "@json@optional()||@json.match(...))"
}
```
(I think both should work fine)

**Pull request closed without merging**
