### PR TITLE
Fix After/Before expanders error message when date/time is equal to boundary

### PR DESCRIPTION
**Pull request by StephaneLeveugle**
<h2>Change Log</h2>
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
    <li>Test coverage of both expanders</li>
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
    <li>Error handling of after/before expanders when value was equal to boundary</li>
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
    <li>Moved much of the code into an abstract class</li>
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    <li>Explicit handling of Time</li>
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>
<hr/>

<h2>Description</h2>

Hi,

I encountered a bug trying to use the after/before expanders when it wouldn't match because the value was equals to the boundary.
No error was set by the expander, which would result to a type error in DateMatcher line 54 (matcherFailed method expected a string as its 4th parameter and null was given)

```php
$this->backtrace->matcherFailed(self::class, $value, $pattern, $this->error);
```

While trying to fix it I saw that the explicit handling of Time was never reached because in the constructor it first checks if the boundary is a DateTime and any Time will be a valid DateTime as we can see in the Time::fromString method

```php
$this->boundaryDateTime = DateTime::fromString($boundary);
```

I added tests to increase the coverage of the expanders and removed any explicit handling of Time.

Finally, given how similar the expanders were I created an abstract class to remove the code duplication I hope that's fine by you.

Please tell me if I missed something and thank you for this much needed library!

### CODE REVIEW

**Comment by norberttech** [comment]
Hey @StephaneLeveugle good catch!! 
Could you take a look at PHP 8.2 and 8.3 tests before I can fully review it and merge? 

> Finally, given how similar the expanders were I created an abstract class to remove the code duplication I hope that's fine by you.

Normally I'm not a huge fan of abstract classes since I prefer composition over inheritance but I don't mind it here that much. If you could extract common logic to a standalone, testable class and then pass it to different types of comparisons it would be perfect but that's not blocking merging of this PR from my point of view.

**Comment by StephaneLeveugle** [comment]
What do you think of traits? The abstract class could easily be a trait.

To be honest I'd rather have a trait because I don't really like inheritance as well, a glorified copy paste is more what I had in mind originally.

I'll take a look at the tests, that's weird because I had php 8.3 installed locally :thinking:

**Comment by norberttech** [comment]
trait works as well, I prefer it over abstract class 👍

**Comment by StephaneLeveugle** [comment]
The tests fail because I used the non deprecated method `isAfterOrEqualTo` instead of `isAfterOrEqual` and the method doesn't exist in older versions of Aeon Calendar library

So we can:
- keep using the non deprecated method and up the requirement of the `aeon-php/calendar` library in composer.json 
- use the deprecated method instead

I'd rather use option 1 but that's up to you

**Comment by norberttech** [comment]
lets go with option number one

**Comment by norberttech** [comment]
huh I have no idea what's happening with the mutation tests, @StephaneLeveugle let me know if you need any help with resolving that

**Comment by StephaneLeveugle** [comment]
I'll take a look, hopefully tonight

**Comment by StephaneLeveugle** [comment]
There was an incompatibility between nikic/php-parser which has been upgraded to v5 and infection/infection which was still in v0.26

I tried to upgrade infection to v0.28 to support nikic/php-parser v5, but I couldn't because of vimeo/psalm which requires v4 of nikic/php-parser

So I decided to lock nikic/php-parser to v4 in the project, are you fine with it?

**Comment by norberttech** [comment]
> So I decided to lock nikic/php-parser to v4 in the project, are you fine with it?

That's perfectly fine, I'm anyway going to split tools into standalone composer.json files like I did [here](https://github.com/flow-php/flow/tree/1.x/tools) to avoid such conflicts. 

Thanks for your contribution!

**Pull request merged**
